# Generated by Django 4.1.4 on 2022-12-28 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('chocies', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Electronic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('items', models.CharField(choices=[('table', 'tabel'), ('chair', 'chair'), ('sofa', 'sofa')], default=None, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Furiniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('items', models.CharField(choices=[('table', 'tabel'), ('chair', 'chair'), ('sofa', 'sofa')], default=None, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produts_name', models.CharField(blank=True, choices=[('sugar', 'sugar'), ('chocolate', 'chocolate')], default=None, max_length=20)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('quanity', models.CharField(blank=True, choices=[('grams', 'grams'), ('kilograms', 'kilograms')], default=None, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Stateonery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('items', models.CharField(choices=[('pen', 'pen'), ('books', 'books'), ('penclis', 'pencils')], default=None, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('Products_choice', models.CharField(blank=True, choices=[('GROCEROY', 'groceroy'), ('STATENOERY', 'stateonery'), ('ELECTRONICS', 'electronics'), ('CLOTHING', 'clothing'), ('FURNITURE', 'furniture')], default=None, max_length=30, null=True)),
                ('measurements', models.CharField(blank=True, choices=[('grams', 'grams'), ('kilograms', 'kilograms'), ('counts', 'counts'), ('liters', 'liters')], default=('kilograms', 'kilograms'), max_length=30, null=True)),
                ('Grocery_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.grocery')),
            ],
        ),
    ]
