# Generated by Django 4.1.4 on 2022-12-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('Products_choice', models.CharField(blank=True, choices=[('GROCEROY', 'groceroy'), ('STATENOERY', 'stateonery'), ('ELECTRONICS', 'electronics'), ('NON_ELECTRIONCS', 'nonelctronics')], default=None, max_length=30, null=True)),
            ],
        ),
    ]
