# Generated by Django 4.1.4 on 2022-12-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Products_choice',
        ),
        migrations.AddField(
            model_name='consumer',
            name='Products_choice',
            field=models.CharField(blank=True, choices=[('GROCEROY', 'groceroy'), ('STATENOERY', 'stateonery'), ('ELECTRONICS', 'electronics'), ('NON_ELECTRIONCS', 'nonelctronics')], default=None, max_length=30, null=True),
        ),
    ]
