# Generated by Django 4.1.4 on 2022-12-29 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='Grocery_choice',
        ),
        migrations.DeleteModel(
            name='Grocery',
        ),
    ]
