# Generated by Django 4.1.4 on 2022-12-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_products_products_choice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groceroy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('quanity', models.CharField(blank=True, choices=[('grams', 'grams'), ('kilograms', 'kilograms')], default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stateonery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='consumer',
            name='Products_choice',
            field=models.CharField(blank=True, choices=[('GROCEROY', 'groceroy'), ('STATENOERY', 'stateonery'), ('ELECTRONICS', 'electronics'), ('NON_ELECTRIONCS', 'nonelctronics'), ('CLOTHING', 'clothing'), ('HOMEAPPLIANCES', 'hoeme_appliances'), ('FURNITURE', 'furniture')], default=None, max_length=30, null=True),
        ),
    ]
