# Generated by Django 4.1.4 on 2022-12-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_consumer_grocery_choice_delete_grocery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofproducts', models.CharField(choices=[('sugar', 'sugar'), ('chocolate', 'chocolate')], default=None, max_length=30, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('quanity', models.CharField(blank=True, choices=[('grams', 'grams'), ('kilograms', 'kilograms')], default=None, max_length=30)),
            ],
        ),
    ]
