# Generated by Django 4.1.4 on 2022-12-29 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_grocery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stateonery',
            new_name='Stationery',
        ),
    ]
