# Generated by Django 4.1.4 on 2022-12-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_stateonery_stationery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronic',
            name='items',
            field=models.CharField(choices=[('mobile', 'mobile'), ('laptops', 'laptops'), ('accressoroies', 'accessroies')], default=None, max_length=30, null=True),
        ),
    ]
