# Generated by Django 4.1.4 on 2022-12-27 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_clothing_electronic_furiniture_consumer_groceroy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='clothing',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='electronic',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='furiniture',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='groceroy',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='statenoery',
        ),
    ]
