# Generated by Django 4.1.4 on 2022-12-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_login_signup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
