# Generated by Django 4.1.4 on 2022-12-26 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_signup_email_remove_signup_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
